### ISSUE TITLE
Documento de especificação de requisitos

### ISSUE THREAD

**Issue by eduardoadf21** [es20231/eqp3#11]
- [x] Escopo
- [x] Definição dos requisitos (Funcionais e não funcionais)
- [x] Diagramas de casos de uso
- [x] Protótipos de tela
- [x] Relatórios de caso de uso
- [x] Diagrama de classes

[djavu.pdf](https://github.com/es20231/eqp3/files/11751061/djavu.pdf)

https://docs.google.com/document/d/133nT1qm8T9YykaHBuytWPq8zIPoz6JNWKr-cQLvHbUs/edit

**Comment by armandossrecife** [comment]
Algumas melhorias que devem ser feitas no Documento de Requisitos:

A. Melhorar a organização dos Requisitos Funcionais:
1. Você pode agrupar em um único Requisito Funcional de Alterar Dados do Usuário. Assim fica mais organizado
2. Você pode agrupar em um único Requisito Funcional Alterar Post
3. Você pode agrupar em um Requisito Funcional Selecionar Usuário

B. Melhorar o fluxo dos Casos de Uso no Diagrama de Casos de Uso
1. Esse diagrama deve ser melhorado, pois as ações de Profile, UserTimeLine, list users estão ligadas a Dashboard e não a login.   

C. Geral:
1. Está faltando a tabela que relaciona Requisitos Funcionais com os respectivos Casos de Uso
2. Está faltando os fluxos de exceção dos casos de uso
 Obs: não confunda fluxo alternativo com fluxo de exceção
3. Melhorar o Diagrama de Classes:
	Usuário comenta Post, por tanto a Classe Comment tem relação com Post

Segue link com os respectivos comentários: [Doc comentado](https://drive.google.com/file/d/1RJVnbDdd-KcblwDbVdOfhnjqkXZYMBIc/view?usp=sharing)

**Comment by LUCIANOGFORTES02** [comment]
Professor já estamos concluindo as observações e sugestões de melhorias feitas pelo senhor.
Agradecemos suas observações detalhadas e sua contribuição para aprimorar o Documento de Requisitos.
