### ISSUE TITLE
Tutorial 2: Tutorial de aplicação básica web

### ISSUE THREAD

**Issue by eduardoadf21** [es20231/eqp3#18]
# Tutorial 2: Como criar uma aplicação web básica com o Flask
## Passo 1: Abra o Link
[Tutorial Aplicação Web com o Flask](https://youtu.be/NmAmOX34FNk)

## Passo 2: Criação do aplicativo Flask
Dentro da pasta do projeto, crie um arquivo chamado app.py e abra-o no seu editor de texto ou IDE preferida.
Importe o Flask e crie uma instância do aplicativo:

```Python
from flask import Flask
app = Flask(__name__)
```

## Passo 3: Crie uma rota para a página do aplicativo, onde exibiremos o formulário. 
Para isso importaremos render_template e em seguida criamos uma rota com uma função abaixo:

```Python
from flask import render_template
```
```Python
@app.route('/cadastro')
def cadastro():
    return render_template('cadastro.html')
```
Note que a String inserida em @app.route fará parte do endereço da pagina web, então uma pagina home seria "/home".

## Passo 4: Criação do formulário HTML
Dentro da pasta do projeto crie uma pasta chamada "templates".
Dentro da pasta "templates" crie um arquivo chamado "cadastro.html".
Agora crie seu código html para sua pagina, neste tutorial usaremos o código abaixo:
```html
<!DOCTYPE html>
<html>
<head>
    <title>Formulário de Cadastro de Usuário</title>
</head>
<body>
    <h1>Formulário de Cadastro de Usuário</h1>
    <form action="/dadosdousuario" method="post">
        <label for="username">Usuário:</label>
        <input type="text" id="username" name="username" required><br><br>
        
        <label for="fullname">Nome Completo:</label>
        <input type="text" id="fullname" name="fullname" required><br><br>
        
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required><br><br>
        
        <label for="password">Senha:</label>
        <input type="password" id="password" name="password" required><br><br>
        
        <input type="submit" value="Cadastrar">
    </form>
</body>
</html>
```
Este código irá exibir um formulário pedindo nome de usuário, nome completo, email e senha, e conterá um botão que quando clicado irá redirecionar o usuário para uma pagina onde exibiremos esses valores

## Passo 5: Recebendo os dados
Volte para o arquivo app.py, lá criaremos uma nova função em uma nova rota para que possamos receber e exibir os dados obtidos.
Para isso primeiro precisaremos importar o request
```Python
from Flask import request
```

Em seguida criamos a função com uma nova rota que utilizará o método POST, para cada um dos valores que pedimos no formulário criaremos uma variável para receber esse valor e então imprimiremos na tela o resultado:
```Python
@app.route('/dadosdousuario', methods=['POST'])
def mostra_dados():
    username = request.form['username']
    fullname = request.form['fullname']
    email = request.form['email']
    password = request.form['password']
    
    return f"Dados do Usuario:<br>Nome de Usuário: {username}<br>Nome Completo: {fullname}<br>Email: {email}<br>Senha: {password}"
```

## Passo 6: Rodar a aplicação
Por fim para rodarmos nossa aplicação precisaremos chamar o método "app.run()":
```Python
app.run()
```
Ao executar a aplicação por padrão a aplicação estará hospedada em: http://127.0.0.1:5000, porém como definimos nossa pagina como "/cadastro", precisamos acessar http://127.0.0.1:5000/cadastro, recebendo a seguinte tela:

![Image](https://user-images.githubusercontent.com/112213498/241280078-29db237d-1d72-4282-bf7a-e404822f0264.png)

Em nosso exemplo html, assim que clicarmos no botão "Cadastrar", seremos redirecionados para a pagina http://127.0.0.1:5000/dadosdousuario mostrando que conseguimos obter os dados inseridos no formulário.

![Image](https://user-images.githubusercontent.com/112213498/241279960-2345c8d7-ebae-4dba-8ec9-bcb5a98ea72e.png)

**Comment by armandossrecife** [comment]
Favor corrigir o link do Youtube, pois o comportamento profissional também será levado em consideração durante as etapas do projeto.
